In [7]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv('/Users/hugoramos/Downloads/lumen_Lumen norms for P&G - June 2025.csv')
df

,channel,platform,format,media_type,device,data_source,pct_viewable,av_viewable_time,pct_viewed,av_view_time,apm,recommended_distribution,pct_viewed_1s,pct_viewed_2s,pct_viewed_3s,pct_viewed_4s,pct_viewed_5s,pct_viewed_10s,pct_viewed_20s,pct_viewed_30s
0,Standard Online Banners,Total,Total,Total,Total,LAMP,0.700567,24.202551,0.341636,2.458843,840.029204,"{""distr"":[""lnorm""],""meanlog"":[""0.23413""],""sdlo...",0.198300,0.118000,0.077500,0.054300,0.039800,0.012500,0.002800,0.001000
1,Standard Online Banners,Total,Total,Total,Desktop,LAMP,0.710039,25.949082,0.155306,1.507192,234.075698,"{""distr"":[""lnorm""],""meanlog"":[""-0.15831""],""sdl...",0.068500,0.033000,0.018500,0.011500,0.007600,0.001600,0.000200,0.000100
2,Standard Online Banners,Total,Total,Total,Mobile,LAMP,0.697602,23.646031,0.399969,2.574526,1029.730106,"{""distr"":[""lnorm""],""meanlog"":[""0.28841""],""sdlo...",0.239700,0.144800,0.095900,0.067600,0.049800,0.015800,0.003600,0.001300
3,Standard Online Banners,Total,Skyscraper,Banner,Total,LAMP,0.808735,31.093067,0.102781,0.891257,91.604325,"{""distr"":[""lnorm""],""meanlog"":[""-0.61949""],""sdl...",0.027600,0.009800,0.004500,0.002400,0.001400,0.000200,0.000000,0.000000
4,Standard Online Banners,Total,Wide Skyscraper,Banner,Total,LAMP,0.812030,29.359186,0.128524,1.270377,163.273864,"{""distr"":[""lnorm""],""meanlog"":[""-0.35149""],""sdl...",0.048000,0.021600,0.011700,0.007100,0.004600,0.000900,0.000100,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
380,Social,Linkedin,Total,Total,Total,LAMP,NaN,NaN,0.806189,4.906161,3955.292978,"{""distr"":[""lnorm""],""meanlog"":[""0.92834""],""sdlo...",0.637000,0.468400,0.355700,0.278400,0.223300,0.093700,0.029200,0.012800
381,Social,Linkedin,Feed,Static,Total,LAMP,NaN,NaN,0.815479,2.312509,1885.802564,"{""distr"":[""lnorm""],""meanlog"":[""0.29599""],""sdlo...",0.499000,0.286600,0.179800,0.120300,0.084500,0.022000,0.003900,0.001200
382,Social,Linkedin,Feed,Video,Total,LAMP,NaN,NaN,0.802804,5.866079,4709.312101,"{""distr"":[""lnorm""],""meanlog"":[""1.10704""],""sdlo...",0.667900,0.514200,0.403700,0.324400,0.265900,0.120000,0.040400,0.018500
383,Streaming,Amazon Prime,Total,Total,Total,Modelled blend,NaN,NaN,0.902709,11.343223,10239.628457,Mixed,0.902722,0.834312,0.781272,0.732579,0.686278,0.480619,0.197499,0.015574
384,Video sharing platform,Twitch,Total,Total,Total,Modelled blend,NaN,NaN,0.661865,3.369277,2230.005221,Mixed,0.661835,0.611665,0.569631,0.530309,0.492813,0.330348,0.111267,0.000000

In [9]:
dm = pd.read_excel('/Users/hugoramos/Downloads/lumen_media_mapping.xlsx')
dm.columns

Index(['channel', 'platform', 'media_type', 'media_subtype', 'app_type',
       'publisher'],
      dtype='object')

In [10]:
#Create keys for the column mapping
keys = list(zip(dm['channel'],dm['platform'],dm['media_type']))

#Create mapping dictionaries
media_subtype_map = dict(zip(keys, dm['media_subtype']))
app_type_map = dict(zip(keys, dm['app_type']))
publisher_map = dict(zip(keys, dm['publisher']))

In [17]:
publisher_map

{('Skins', 'Total', 'Total'): nan,
 ('Standard Online Banners', 'Total', 'Banner'): nan,
 ('Standard Online Banners', 'Total', 'Total'): nan,
 ('Standard Online Video', 'Total', 'Video'): nan,
 ('Outstream Video', 'Total', 'Total'): nan,
 ('Streaming', 'Total', 'Video'): nan,
 ('Streaming', 'Total', 'Total'): nan,
 ('Video sharing platform', 'Total', 'Video'): nan,
 ('Video sharing platform', 'Total', 'Total'): nan,
 ('Press', 'Total', 'Total'): nan,
 ('Standard Online Video', 'Total', 'Total'): nan,
 ('High Impact', 'Total', 'Total'): nan,
 ('Magazines', 'Total', 'Total'): nan,
 ('Gaming', 'Total', 'Video'): nan,
 ('Gaming', 'Total', 'Total'): nan,
 ('Gaming', 'Total', 'Banner'): nan,
 ('Cinema', 'Total', 'Total'): nan,
 ('Cinema', 'Total', 'Video'): nan,
 ('OOH', 'Driver', 'Digital'): nan,
 ('OOH', 'Driver', 'Static'): nan,
 ('OOH', 'Internal', 'Digital'): nan,
 ('OOH', 'Internal', 'Static'): nan,
 ('OOH', 'Roadside pedestrian', 'Digital'): nan,
 ('OOH', 'Roadside pedestrian', 'Static'): nan,
 ('OOH', 'Roadside pedestrian', 'Bus'): nan,
 ('OOH', 'Driver', 'Total'): nan,
 ('OOH', 'Internal', 'Total'): nan,
 ('OOH', 'Roadside pedestrian', 'Total'): nan,
 ('OOH', 'Total', 'Bus'): nan,
 ('OOH', 'Total', 'Digital'): nan,
 ('OOH', 'Total', 'Static'): nan,
 ('OOH', 'Total', 'Total'): nan,
 ('Retail Media', 'Co-op', 'Total'): nan,
 ('Social', 'Snapchat', 'Video'): 'Snapchat',
 ('Social', 'Facebook', 'Video'): 'Facebook',
 ('Social', 'Instagram', 'Video'): 'Instagram',
 ('Social', 'Facebook', 'Total'): 'Facebook',
 ('Social', 'Total', 'Total'): nan,
 ('Social', 'Snapchat', 'Total'): 'Snapchat',
 ('Social', 'Pinterest', 'Banner'): 'Pinterest',
 ('Social', 'Instagram', 'Banner'): 'Instagram',
 ('Social', 'Facebook', 'Banner'): 'Facebook',
 ('Social', 'Instagram', 'Total'): 'Instagram',
 ('Social', 'Pinterest', 'Total'): 'Pinterest',
 ('Social', 'Pinterest', 'Video'): 'Pinterest',
 ('Video sharing platform', 'YouTube', 'Video'): 'YouTube',
 ('Video sharing platform', 'Twitch', 'Total'): 'Twitch',
 ('Social', 'Twitter', 'Video'): 'Twitter',
 ('Social', 'Twitter', 'Total'): 'Twitter',
 ('Video sharing platform', 'YouTube', 'Total'): 'YouTube',
 ('Social', 'TikTok', 'Video'): 'TikTok',
 ('Social', 'TikTok', 'Total'): 'TikTok',
 ('Social', 'Linkedin', 'Video'): 'Linkedin',
 ('Social', 'Linkedin', 'Total'): 'Linkedin',
 ('Social', 'Linkedin', 'Static'): 'Linkedin',
 ('Streaming', 'Amazon Prime', 'Total'): 'Amazon Prime Video',
 ('Social', 'Snapchat', 'AR'): 'Snapchat'}

In [18]:
def replace_nan_with_none(key):
    return tuple(None if pd.isna(k) else k for k in key)

media_subtype_map = {
    replace_nan_with_none(k): v
    for k, v in media_subtype_map.items()
}
app_type_map = {
    replace_nan_with_none(k): v
    for k, v in app_type_map.items()
}
publisher_map = {
    replace_nan_with_none(k): v
    for k, v in publisher_map.items()
}

In [19]:
# Create all the column by mapping each row
df["media_subtype"] = df.apply(
    lambda row: media_subtype_map.get((row["channel"],row["platform"],row["media_type"])),
    axis=1)

df["app_type"] = df.apply(
    lambda row: app_type_map.get((row["channel"],row["platform"],row["media_type"])),
    axis=1)

df["publisher"] = df.apply(
    lambda row: publisher_map.get((row["channel"],row["platform"],row["media_type"])),
    axis=1)

In [20]:
df

,channel,platform,format,media_type,device,data_source,pct_viewable,av_viewable_time,pct_viewed,av_view_time,...,pct_viewed_2s,pct_viewed_3s,pct_viewed_4s,pct_viewed_5s,pct_viewed_10s,pct_viewed_20s,pct_viewed_30s,media_subtype,app_type,publisher
0,Standard Online Banners,Total,Total,Total,Total,LAMP,0.700567,24.202551,0.341636,2.458843,...,0.118000,0.077500,0.054300,0.039800,0.012500,0.002800,0.001000,NaN,NaN,NaN
1,Standard Online Banners,Total,Total,Total,Desktop,LAMP,0.710039,25.949082,0.155306,1.507192,...,0.033000,0.018500,0.011500,0.007600,0.001600,0.000200,0.000100,NaN,NaN,NaN
2,Standard Online Banners,Total,Total,Total,Mobile,LAMP,0.697602,23.646031,0.399969,2.574526,...,0.144800,0.095900,0.067600,0.049800,0.015800,0.003600,0.001300,NaN,NaN,NaN
3,Standard Online Banners,Total,Skyscraper,Banner,Total,LAMP,0.808735,31.093067,0.102781,0.891257,...,0.009800,0.004500,0.002400,0.001400,0.000200,0.000000,0.000000,Digital Display,NaN,NaN
4,Standard Online Banners,Total,Wide Skyscraper,Banner,Total,LAMP,0.812030,29.359186,0.128524,1.270377,...,0.021600,0.011700,0.007100,0.004600,0.000900,0.000100,0.000000,Digital Display,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
380,Social,Linkedin,Total,Total,Total,LAMP,NaN,NaN,0.806189,4.906161,...,0.468400,0.355700,0.278400,0.223300,0.093700,0.029200,0.012800,Social,Social,Linkedin
381,Social,Linkedin,Feed,Static,Total,LAMP,NaN,NaN,0.815479,2.312509,...,0.286600,0.179800,0.120300,0.084500,0.022000,0.003900,0.001200,Social,Social,Linkedin
382,Social,Linkedin,Feed,Video,Total,LAMP,NaN,NaN,0.802804,5.866079,...,0.514200,0.403700,0.324400,0.265900,0.120000,0.040400,0.018500,Social,Social,Linkedin
383,Streaming,Amazon Prime,Total,Total,Total,Modelled blend,NaN,NaN,0.902709,11.343223,...,0.834312,0.781272,0.732579,0.686278,0.480619,0.197499,0.015574,OTT,Hybrid SVOD/AVOD,Amazon Prime Video
384,Video sharing platform,Twitch,Total,Total,Total,Modelled blend,NaN,NaN,0.661865,3.369277,...,0.611665,0.569631,0.530309,0.492813,0.330348,0.111267,0.000000,OTT,AVOD,Twitch

In [21]:
df.to_parquet('lumne.parquet')